### ISSUE TITLE
train code

### ISSUE THREAD

**Issue by wangyanli3630** [THUDM/AgentTuning#1]
May I ask if there is code available for training agentLM?

**Comment by Btlmd** [comment]
We used an internal training framework for AgentLM. I'm sorry to say that due to some restrictions, we cannot release the training code immediately. However, you may consider using many other open source training frameworks to finetune with our released dataset.

**Comment by yt7589** [comment]
Can I use ptuning v2 or LoRA to finetune this model?

**Comment by Btlmd** [comment]
Sure! The models can be finetuned just like Llama-2-chat. Scripts working for Llama-2-chat should also work for AgentLM models.
