### ISSUE TITLE
论文中关于损失函数E的问题

### ISSUE THREAD

**Issue by Dhaizei** [THUDM/AgentTuning#10]
您好，看了下您这边的论文，是针对最后损失loss进行修改吗？其中J(θ) = η · E(x,y)∼Dagent [log πθ (y | x)] + (1 − η) · E(x,y)∼Dgeneral [log πθ (y | x)]       E（x,y）在论文中并没有找到对应的解释说明，是CE—loss吗

**Comment by Sengxian** [comment]
其实就是按比例采样进行微调训练，论文中只是给出一个损失函数的形式化表达方式～

**Comment by Dhaizei** [comment]
好的，谢谢您~

**Comment by Dhaizei** [comment]
我想问一下，论文中所说，general domain instruction 是anon8231489123/ShareGPT_Vicuna_unfiltered  中no_imsorry这个json文件中的数据吗？，我发现你们做了一个事情，是将gpt4和3.5的对话区分出来了，这个是怎么做到的呢？是从openchat/openchat_sharegpt_v3这个数据集里面挑选的吗？还是通过上面的那个数据集？
期待您的回复~

**Comment by Dhaizei** [comment]
还有想问一下，最后sharegpt用了多少呢是57,096 conversations with GPT-3.5 and 3,670  一共60766条吗？和agenttuning的1866条数据吗？
期待您的回复~

**Comment by Dhaizei** [comment]
用您这边的数据对llama2 chat进行了 微调，一开始的loss是1.35，最后是0.4 ，就设了一轮，是不是有点过拟合了呢？
![image](https://github.com/THUDM/AgentTuning/assets/92254983/be9da15b-9feb-48d8-9b12-baeeef0dd34c)

**Comment by Btlmd** [comment]
我们使用了内部版本对 ShareGPT 数据集的数据来源标签。您可以考虑使用 [OpenChat](https://huggingface.co/openchat) 提供的开源 GPT-3.5/4 的数据进行混合训练。

---

我们用了 57,096 条 GPT-3.5 的轨迹，3,670 条 GPT-4 的轨迹，以及 1866 条 AgentInstruct 轨迹，按照论文附录中的配比

---

对于 Llama-2-chat-7b，我们混训微调时的初始 loss 约为 1，终止 loss 约为 1e-1。我认为 loss 4e-1 并不算过拟合。

**Comment by Dhaizei** [comment]
请问，是如何做到混合数据集也能微调到loss为1e-1的呢？我在做混合指令微调的时候，发现加入sharegpt的数据，一直震荡在0.7左右，而单训练AgentInstruct 可以很好的拟合到loss为1e-1，你们一共做了多少轮训练呢？我单独训练AgentInstruct的效果并不是很好，在HH方面，我epoch=3，最后测评，仅有一个是跑对的，其余都是无效action
