### ISSUE TITLE
Model Output Length

### ISSUE THREAD

**Issue by HeimingX** [THUDM/AgentTuning#11]
Hi, thanks for the interesting work and awesome codebase. Recently, I tested the 7b model with TGI (used config file: docker/agentlm-7b.yml) and I just found that the model's output seems to be trunked:

Query: I want to have a journey to California, please help me to build up a tourism plan. Please think step by step.
Answer: {"generated_text":"Sure, I'd be happy to help you plan a tour of California! Here's a"}

I wonder if I need to revise the config to enable the model to generate more words. Many thanks

**Comment by Btlmd** [comment]
You may consider adding `"parameters":{"max_new_tokens":20}}` in request JSON.
See https://huggingface.github.io/text-generation-inference/#/Text%20Generation%20Inference/generate for a detailed description of `/generate`

**Comment by HeimingX** [comment]
thanks, it works.
