### ISSUE TITLE
论文中的问题

### ISSUE THREAD

**Issue by QingChengLineOne** [THUDM/AgentTuning#16]
Recognizing the superior quality of GPT-4 responses as highlighted by (Wang et al., 2023a), we adopted a sampling ratio of 1:4 between GPT-4 and GPT-3.5 for better performance.
GPT-4的响应质量不是更高吗，为什么采样比例GPT-4反而低呢？

**Comment by Sengxian** [comment]
因为 GPT-4 数据少， 57,096 条 GPT-3.5，3,670 条 GPT-4，这个比例已经是上采样了。
