### ISSUE TITLE
论文中Table 2中的数字的含义和计算方式

### ISSUE THREAD

**Issue by DryPilgrim** [THUDM/AgentTuning#17]
可以解释一下Table 2中的数字的含义和计算方式吗 ：）

Table 2: Ablation study on trajectory filtering.

**Comment by lr-tsinghua11** [comment]
计算方式和Table 4中的overall一样，对所有任务取加权平均（权重见Table 3）。该实验主要表明如果不对gpt-4的交互数据filter，模型在Agent任务上性能会有所下降。

**Comment by DryPilgrim** [comment]
感谢：）
