### ISSUE TITLE
Inference with `vllm`

### ISSUE THREAD

**Issue by yc1999** [THUDM/AgentTuning#29]
Hi, thanks for ur great work!
I notice that you use [Text-Generation-Inference](https://github.com/huggingface/text-generation-inference) to accelerate the evaluation process.
Does your model work with `vllm`?

**Comment by Btlmd** [comment]
I haven't tested the checkpoints in vLLM yet. However, as we made no modifications to the model 
architecture of Llama-2, AgentLM should be able to run at any platform that supports  Llama-2.
