### ISSUE TITLE
AgentLM能支持openai.api类的接口本地部署吗？

### ISSUE THREAD

**Issue by HuntZhaozq** [THUDM/AgentTuning#3]
请问AgentLM能支持openai.api类的接口本地部署吗？尝试用了fastchat进行部署，提示说找不到这个模型。请问AgentLM如何进行openai.api类的部署？

**Comment by HuntZhaozq** [comment]
测了下可以fastchat部署，但是效果好像一般

**Comment by YinSonglin1997** [comment]
> 测了下可以fastchat部署，但是效果好像一般

请问您在fastchat部署后，对Agentbench进行评测成功了吗？我也用fastchat部署了，但只是简单的推理，评测的时候就会报错
