### ISSUE TITLE
请教reward分数的各种情况

### ISSUE THREAD

**Issue by DryPilgrim** [THUDM/AgentTuning#30]
reward出现了以下情况：
1.论文第2节说”Each trajectory has a final reward **r ∈ [0, 1]**, reflecting the completion status of the task。“
2.论文第2.1.3节说 "due to the difficulty of the Mind2Web task, we use a threshold of r ≥ 2/3 to ensure we obtain a sufficient number of trajectories."
3. 论文”AgentBench: Evaluating LLMs as Agents“ 第E.1节说 ”ultimately we provide a final reward score according to the above metrics:
  reward = 0.7 × metricwinrate + 0.3 × metricdamagerate“
4.论文”AgentBench: Evaluating LLMs as Agents“ 第H.1节说 ”As there might be more than one suitable item for a given query, Webshop adopts a matching reward as its evaluation metric:“ 
$$ Reward =\frac{|Uatt ∩ Yatt| + |Uopt ∩ Yopt| + I[yprice ≤ uprice]}{|Uatt| + |Uopt| + 1}·rtype $$

请教作者：
- 1和2冲突了？（1说r的取值范围只有0和1）
- 3和4的公式分别是计算DCG和WB的r, 那本文中各个任务的r计算公式分别是啥呀？

**Comment by lr-tsinghua11** [comment]
+ [0, 1] 是区间
+ E.1 节是对 Digital Card Game 的 reward 计算说明，AgentInstruct 没有 DCG，DCG 属于 Held-out 外分布数据集
+ 由 rtype ≤ 1 可以证明
![](https://latex.codecogs.com/svg.image?r=\frac{|Uatt\cap&space;Yatt|&plus;|Uopt\cup&space;Yopt|&plus;\mathbb{I}[yprice\geq&space;uprice]}{|Uatt|&plus;|Uopt|&plus;1}\cdot&space;rtype\in[0,1])
+ 本文的 reward 计算公式与 AgentBench 保持一致，具体指标可参考 AgentTuning Table 3 以及 AgentBench 相关公式
