### ISSUE TITLE
requests.exceptions.MissingSchema: Invalid URL '127.0.0.123332/generate': No scheme supplied. Perhaps you meant https://127.0.0.123332/generate?

### ISSUE THREAD

**Issue by mayilin0714** [THUDM/AgentTuning#31]
<img width="1040" alt="image" src="https://github.com/THUDM/AgentTuning/assets/71692462/c892a4a6-ed14-446e-8ead-100fe70a7766">
requests.exceptions.MissingSchema: Invalid URL '127.0.0.123332/generate': No scheme supplied. Perhaps you meant https://127.0.0.123332/generate?

您好，我在运行python eval_general/eval_gsm8k_tgi.py --port 30070出现了上述问题，请问如何解决呢？

**Comment by lr-tsinghua11** [comment]
Thanks for your feedback! See newest commit.
感谢你的反馈，最新 commit 修复了这个问题~
(127.0.0.123332 -> 127.0.0.1:23332)
