### ISSUE TITLE
agent tuning和toolbench的区别

### ISSUE THREAD

**Issue by Connor-Shen** [THUDM/AgentTuning#34]
之前读过你们toolbench的论文，感觉数据集构建和指令微调的思路也和这篇agent tuning差不太多。
想请教一下两篇paper的差别和侧重点，非常感谢！

**Comment by Btlmd** [comment]
感谢您的关注。
我觉得侧重点有这么几个不同。任务上，AgentTuning 探索的几类 Agent 任务相比简单的工具调用来说，任务的目标更复杂，需要模型完成的交互轮数平均更多，同时 held-out 任务的类型与 held-in 也有较大差异；训练策略上，AgentTuning 使用混合训练的方法，将少量 Agent 交互数据与大量通用数据混训，在提升模型的 Agent 能力时几乎不损失模型通用能力。
