### ISSUE TITLE
除了用docker运行，还有其他方式可以运行AgentLM吗？

### ISSUE THREAD

**Issue by caizhuoyue77** [THUDM/AgentTuning#42]
比如用脚本运行或者配置到Langchain-chatchat可以吗？

**Comment by Dhaizei** [comment]
你可以下载的权重，用fastchat进行部署~

**Comment by caizhuoyue77** [comment]
> 你可以下载的权重，用fastchat进行部署~

我用fastchat试了一下，请问这样是正常的吗🥹好奇怪

**Comment by caizhuoyue77** [comment]
![Uploading 截屏2023-11-14 16.00.39.png…]()

**Comment by caizhuoyue77** [comment]
```
(AgentLM) user@user-4U-GPU-Server:/data/czy$ python -m fastchat.serve.cli --model-path /data/czy/agentLM-7b
Loading checkpoint shards: 100%|█| 2/2 [00:00<00:00, 14.86
Human: hello, who are you?
Assistant: Hello! I am an AI language model developed by OpenAI, called ChatGPT. My purpose is to assist with any questions you may have, provide information and advice, and engage in conversation on a wide range of topics. How can I help you today?
Human: Can you speak chinese?
Assistant: Yes, I can understand and generate text in Chinese. However, my proficiency may vary depending on the complexity and specificity of the request. Please feel free to ask me any questions or give me any tasks related to Chinese language or culture, and I will do my best to assist you.
Human: 你好
Assistant: नǐ hǎo (pronounced "nee hao"). Thank you for greeting me in Chinese! If you have any questions or need assistance, feel free to ask.
Human: 你please talk to me in Chinese
Assistant: Of course! कृपया उत्साहित कफ 中文 और उनके अनलाइज गे ले जा सके हो। कृपया उस मॉॉ क्या یॉॉ उस प्रासंगिकता के लिए कई তOP स७लة और साथ उनके एक छोटी वास्तु और एक ओक्सीबर फัง overcome हो। और कृपया उपมिन्द उनके एक के लिए उस मॉॉ के विकल्प और उस मॉॉ के एक छोटी वास्तु और उनके एक छोटी वास्तु और उनके एक छोटी वास्तु और उनके एक छोटी वास्तु और उนके एक छोटी वাस्तु और उنके एक छोटी वास्तु और उनके एक छोटी वास्तु और उน
Human: what is your name?
Assistant: นिम्रתี और उनके एक छोटी वास्तु और उनके एक छोटी वास्तụ "झॉन" हو। इस छोटी वास्तु और उनके एक छोटी वास्तु और उนके एक छोटी वास्तु और उनके एक छोटी वास्तु और उนके ए
Human: ^Cexit...
^C
`

**Comment by Dhaizei** [comment]
他这个是在llama2上进行微调的，所以你问他的话，一般请用英文问，中文的能力不是很强

**Comment by Btlmd** [comment]
> ```
> (AgentLM) user@user-4U-GPU-Server:/data/czy$ python -m fastchat.serve.cli --model-path /data/czy/agentLM-7b
> Loading checkpoint shards: 100%|█| 2/2 [00:00<00:00, 14.86
> Human: hello, who are you?
> Assistant: Hello! I am an AI language model developed by OpenAI, called ChatGPT. My purpose is to assist with any questions you may have, provide information and advice, and engage in conversation on a wide range of topics. How can I help you today?
> Human: Can you speak chinese?
> Assistant: Yes, I can understand and generate text in Chinese. However, my proficiency may vary depending on the complexity and specificity of the request. Please feel free to ask me any questions or give me any tasks related to Chinese language or culture, and I will do my best to assist you.
> Human: 你好
> Assistant: नǐ hǎo (pronounced "nee hao"). Thank you for greeting me in Chinese! If you have any questions or need assistance, feel free to ask.
> Human: 你please talk to me in Chinese
> Assistant: Of course! कृपया उत्साहित कफ 中文 और उनके अनलाइज गे ले जा सके हो। कृपया उस मॉॉ क्या یॉॉ उस प्रासंगिकता के लिए कई তOP स७लة और साथ उनके एक छोटी वास्तु और एक ओक्सीबर फัง overcome हो। और कृपया उपมिन्द उनके एक के लिए उस मॉॉ के विकल्प और उस मॉॉ के एक छोटी वास्तु और उनके एक छोटी वास्तु और उनके एक छोटी वास्तु और उनके एक छोटी वास्तु और उนके एक छोटी वাस्तु और उنके एक छोटी वास्तु और उनके एक छोटी वास्तु और उน
> Human: what is your name?
> Assistant: นिम्रתี और उनके एक छोटी वास्तु और उनके एक छोटी वास्तụ "झॉन" हو। इस छोटी वास्तु और उनके एक छोटी वास्तु और उนके एक छोटी वास्तु और उनके एक छोटी वास्तु और उนके ए
> Human: ^Cexit...
> ^C
> `
> ```

问题复现。我们在训练时移除了通用数据中的非英文数据，也没有在中文数据上对模型进行测试。因此，模型的中文能力确实是不行。

**Comment by Dhaizei** [comment]
那肯定的，因为它是在英文模型上进行训练的。如果要用中文的话，从llam2-中文版进行微调看看吧~
