### ISSUE TITLE
Finetuning with Mistral or Yi?

### ISSUE THREAD

**Issue by jFkd1** [THUDM/AgentTuning#43]
As titled. Are there plans to use a newer base model to finetune agents, such as Mistral 7B or Yi 34B?

**Comment by lr-tsinghua11** [comment]
Thank you for your question. As of now, we do not have immediate plans to finetune newer base models such as Mistral 7B or Yi 34B. However, if needed, you are welcome to use _AgentInstruct_ dataset for finetuning to adapt the models to your specific requirements.
