### ISSUE TITLE
是否可以不在docker里运行

### ISSUE THREAD

**Issue by QingChengLineOne** [THUDM/AgentTuning#5]
我想在服务器上运行代码，是否可以不用docker，能否提供一下比较推荐的python安装版本

**Comment by Prudhvi-232** [comment]
当在服务器上运行Python代码时，您通常可以选择直接安装Python而不使用Docker，尤其是在服务器上没有特殊要求或隔离的情况下。以下是一些推荐的Python安装版本：

1. **Python 3.7+**: Python 2已经不再得到官方支持，因此请确保您使用Python 3的最新版本。目前（截止到我的知识截止日期是2021年），Python 3.7及更高版本是不错的选择。

2. **Python 3.8+**: Python 3.8引入了一些新功能和性能改进，因此如果可能的话，选择Python 3.8或更高版本是一个好主意。

3. **Python 3.9+**: Python 3.9还引入了新特性和性能改进，也是一个不错的选择。

4. **Python 3.10+**: 如果您想使用最新的Python版本，可以选择Python 3.10或更高版本，但要确保您的代码和依赖项与新版本兼

**Comment by QingChengLineOne** [comment]
在conda中装好虚拟环境后，我该怎么运行 AgentLM并进行评测呢？

**Comment by Prudhvi-232** [comment]
在 Conda 中设置好虚拟环境后，要运行 AgentLM 并进行评测，可以按照以下步骤进行：

1. 激活虚拟环境：
   ```
   conda activate your_virtual_environment_name
   ```

   请将 `your_virtual_environment_name` 替换为你创建的虚拟环境名称。

2. 进入 AgentLM 的目录：
   ```
   cd path_to_AgentLM_directory
   ```

   请将 `path_to_AgentLM_directory` 替换为 AgentLM 代码所在的文件夹路径。

3. 运行 AgentLM：
   ```
   python agentlm.py
   ```

   这将启动 AgentLM 程序。

4. 执行评测：
   根据 AgentLM 的具体功能和用途，使用相应的命令或参数来进行评测。通常，你需要提供输入数据或配置文件，以便 AgentLM 进行评测任务。

请确保你已经正确设置了虚拟环境，并在正确的目录中运行 AgentLM。此外，要根据 AgentLM 的文档或指南查看详细的评测方法和选项。

**Comment by Btlmd** [comment]
如果无法启动 Docker，Text Generation Inference 也可以[不使用 Docker 而直接构建](https://github.com/huggingface/text-generation-inference#local-install)
如果不想使用 TGI，可以参考 [FastChat](https://github.com/lm-sys/FastChat) 中运行 llama-2-chat 的方式来启动 ModelWorker；并修改目前针对 tgi 框架的评测脚本，在通讯协议上适配 FastChat Controller 和 FastChat ModelWorker 即可

---

2 posts deleted, seems to be generated by bots.
