### ISSUE TITLE
Can you point to the ShareGPT filtered/cleaned data used?

### ISSUE THREAD

**Issue by harshraj172** [THUDM/AgentTuning#50]
Hey, thank you for your great work. I was replicating the training of AgentLM and was searching for the ShareGPT data used. The paper mentions [this](https://huggingface.co/datasets/anon8231489123/ShareGPT_Vicuna_unfiltered) as the data used but I cannot find the filtered/cleaned version anywhere. Can you pls tell how to get the final version of the ShareGPT data used for training AgentLM?

**Comment by Btlmd** [comment]
We used an internal version of ShareGPT to filter and classify the general data we use, and I'm afraid that we cannot open-source it immediately. 

For cleaned and classified datasets, you may consider using ShareGPT datasets provided by [OpenChat](https://huggingface.co/openchat), like [openchat_sharegpt_v3](https://huggingface.co/datasets/openchat/openchat_sharegpt_v3) and [openchat_sharegpt_v4](https://huggingface.co/datasets/openchat/openchat_sharegpt4_dataset) as an alternative.
