### ISSUE TITLE
训练数据是如何采样的？

### ISSUE THREAD

**Issue by Fu-Dayuan** [THUDM/AgentTuning#52]
我观察到 #36 里面说一共进行了2000个step，所以应该有2000x64=128000个样本，考虑到 &eta = 0.2，所以sharegpt的数据应该为102400，但是 #16 中说这个数据已经是上采样了，这之间的gap是为什么呢？
以及考虑到 &eta = 0.2 所以是把agenttuning的数据在一个epoch里上采样了60000 * 0.2 / 1800 = 8倍吗？（具体来说，在2000个step下，每个agenttuning/sharept样本大概被训练了几次呢？）
还有你们为什么会选择sharegpt用60000这个数据量呢？（而不是10000或者40000之类的）

**Comment by Fu-Dayuan** [comment]
（补充）我看alfworld数据集里一共有4000+个数据，为什么在论文中说数据集只有900+（同样的，webshop有6000+，论文里说有1400+）

**Comment by Btlmd** [comment]
> 我观察到 #36 里面说一共进行了2000个step，所以应该有2000x64=128000个样本，考虑到 &eta = 0.2，所以sharegpt的数据应该为102400，但是 #16 中说这个数据已经是上采样了，这之间的gap是为什么呢？ 以及考虑到 &eta = 0.2 所以是把agenttuning的数据在一个epoch里上采样了60000 * 0.2 / 1800 = 8倍吗？（具体来说，在2000个step下，每个agenttuning/sharept样本大概被训练了几次呢？） 还有你们为什么会选择sharegpt用60000这个数据量呢？（而不是10000或者40000之类的）

- #16 中说的"上采样"是指调高了 GPT-4 的数据相对于 GPT-3.5 数据的占比
- 我们在训练的过程中使用了 packing，并未严格统计各数据集训练的 epoch 数。按不计 packing 来估算，各数据集至少训练的次数为
  - GPT-4 Data 2000 * 64 * 0.8 * 0.2 / 3670 = 5.58
  - GPT-3.5 Data 2000 * 64 * 0.8 * 0.8 / 57069 =  1.44
  - AgentInstruct Data 2000 * 64 * 0.2  / 1866 = 13.72
- General Data 的数据量是根据我们当时所有的 ShareGPT 数据的数量确定的（当时只有这些 General 数据）

**Comment by lr-tsinghua11** [comment]
> 我看alfworld数据集里一共有4000+个数据，为什么在论文中说数据集只有900+（同样的，webshop有6000+，论文里说有1400+）

AlfWorld & Webshop 任务相对简单，我们并没有推理全部的数据集就已经收集到较多的高质量历史交互轨迹。
