### ISSUE TITLE
交互轨迹的Reward如何得到

### ISSUE THREAD

**Issue by jiezhangGt** [THUDM/AgentTuning#8]
论文中的交互轨迹的Reward如何得到？用什么进行打分？

**Comment by lr-tsinghua11** [comment]
The trajectory is derived from AgentBench's evaluation results. 
Details at [AgentBench.old](https://github.com/THUDM/AgentTuning/tree/main/AgentBench.old) or [THUDM/AgentBench](https://github.com/THUDM/AgentBench)
交互轨迹来源于 AgentBench 的评测结果。
具体细节 [AgentBench.old](https://github.com/THUDM/AgentTuning/tree/main/AgentBench.old) 或 [THUDM/AgentBench](https://github.com/THUDM/AgentBench)
