### ISSUE TITLE
微调

### ISSUE THREAD

**Issue by Dhaizei** [THUDM/AgentTuning#9]
麻烦大神回答了！
有没有微调过程成的细节？
直接就用fastchat的那个微调的代码吗？
期待您的回复~

**Comment by Btlmd** [comment]
如 #1 所说，我们使用内部训练框架完成了 AgentLM 的训练，目前我们无法立即开源训练代码。
我们所开源的数据集使用 [FastChat](https://github.com/lm-sys/FastChat) 对应的输入格式；您也可以使用 FastChat 来继续微调 AgentLM 或使用 AgentInstruct 数据集来微调其他模型。

**Comment by Dhaizei** [comment]
感谢您的回复~
